name: Предложение улучшения
description: Предложить новую функцию или улучшение
labels: [enhancement]
body:
  - type: textarea
    id: problem
    attributes:
      label: Какую проблему это решает
      description: Опишите ситуацию, с которой вы столкнулись
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Предлагаемое решение
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Рассмотренные альтернативы
    validations:
      required: false
